const firebaseConfig = {
  API_KEY: process.env.NEXT_PUBLIC_API_KEY,
  AUTH_DOMAIN: process.env.NEXT_PUBLIC_AUTH_DOMAIN,
  PROJECT_ID: process.env.NEXT_PUBLIC_PROJECT_ID,
  STORAGE_BUCKET: process.env.NEXT_PUBLIC_STORAGE_BUCKET,
  MESSAGING_SENDER_ID: process.env.NEXT_PUBLIC_MESSAGING_SENDER_ID,
  APP_ID: process.env.NEXT_PUBLIC_APP_ID,
  ADMIN_CLIENT_EMAIL: process.env.NEXT_PUBLIC_ADMIN_CLIENT_EMAIL,
  ADMIN_PRIVATE_KEY: process.env.NEXT_PUBLIC_ADMIN_PRIVATE_KEY,
  SESSION_COOKIE_NAME: process.env.NEXT_PUBLIC_SESSION_COOKIE_NAME
}

export default firebaseConfig